### ISSUE TITLE
The SVN repo

### ISSUE THREAD

**Issue by jmcejuela** [Rostlab/PROFsec#1]
* [x] Search exhaustively where the PROFsec repos could be located (it's actually used in PredictProtein so **it must be somewhere** -- Don't doubt to ask me @jmcejuela for more help.
* [x] Verify whether `reprof` replaces PROFsec

---

Originally written by @rocreguant 

```
Dear Juan Miguel,
I've been searching for PROFsec in the websites you provided but I couldn't find it.
Can it be somewhere else? or the name might be something else?
PS: Protein Prediction 2 the SVN => Git
Best,
Roc Reguant
```

**Comment by jmcejuela** [comment]
@rocreguant good point. I couldn't find the repos myself either. However, by using the PredictProtein.org service, I found out that the tool is supposedly replaced by `reprof`. You can find the repos for it at: https://github.com/Rostlab/PP2_CS_WS_2015-16/blob/master/README.md#tools

Please, still try to search `somewhere...` where the original PROFsec code is. And whether `reprof` can indeed replace the latter.

**Comment by jmcejuela** [comment]
More info: https://github.com/Rostlab/PP2_CS_WS_2015-16/wiki/HOWTO-access-rostlab-svn-repos

**Comment by rocreguant** [comment]
The SVN url provided is the correct one. The Github repository provided is not the same nor a newer version (is coded in C vs perl).
reprof == PROFsec
Thanks!
Closing issue.

**Comment by jmcejuela** [comment]
reprof == PROFsec ? Wow, didn't know :)

On Thursday you present your findings :) Cheers
